FROM ghcr.io/open-webui/pipelines:main
LABEL authors="eresque"

COPY OpenWebUI/pipelines/requirements.txt ./extra_requirements.txt
RUN pip install -r ./extra_requirements.txt

COPY OpenWebUI/pipelines/generation.py ./pipelines

ENTRYPOINT [ "bash", "start.sh" ]
